/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinGameRouteImport } from './routes/join-game'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HostLobbyRouteImport } from './routes/host-lobby'
import { Route as CreateGameRouteImport } from './routes/create-game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteGameIdRouteImport } from './routes/vote.$gameId'
import { Route as LobbyGameIdRouteImport } from './routes/lobby.$gameId'

const JoinGameRoute = JoinGameRouteImport.update({
  id: '/join-game',
  path: '/join-game',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HostLobbyRoute = HostLobbyRouteImport.update({
  id: '/host-lobby',
  path: '/host-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGameRoute = CreateGameRouteImport.update({
  id: '/create-game',
  path: '/create-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteGameIdRoute = VoteGameIdRouteImport.update({
  id: '/vote/$gameId',
  path: '/vote/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyGameIdRoute = LobbyGameIdRouteImport.update({
  id: '/lobby/$gameId',
  path: '/lobby/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/host-lobby': typeof HostLobbyRoute
  '/join': typeof JoinRoute
  '/join-game': typeof JoinGameRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/vote/$gameId': typeof VoteGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/host-lobby': typeof HostLobbyRoute
  '/join': typeof JoinRoute
  '/join-game': typeof JoinGameRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/vote/$gameId': typeof VoteGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/host-lobby': typeof HostLobbyRoute
  '/join': typeof JoinRoute
  '/join-game': typeof JoinGameRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/vote/$gameId': typeof VoteGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-game'
    | '/host-lobby'
    | '/join'
    | '/join-game'
    | '/lobby/$gameId'
    | '/vote/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-game'
    | '/host-lobby'
    | '/join'
    | '/join-game'
    | '/lobby/$gameId'
    | '/vote/$gameId'
  id:
    | '__root__'
    | '/'
    | '/create-game'
    | '/host-lobby'
    | '/join'
    | '/join-game'
    | '/lobby/$gameId'
    | '/vote/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateGameRoute: typeof CreateGameRoute
  HostLobbyRoute: typeof HostLobbyRoute
  JoinRoute: typeof JoinRoute
  JoinGameRoute: typeof JoinGameRoute
  LobbyGameIdRoute: typeof LobbyGameIdRoute
  VoteGameIdRoute: typeof VoteGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-game': {
      id: '/join-game'
      path: '/join-game'
      fullPath: '/join-game'
      preLoaderRoute: typeof JoinGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-lobby': {
      id: '/host-lobby'
      path: '/host-lobby'
      fullPath: '/host-lobby'
      preLoaderRoute: typeof HostLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-game': {
      id: '/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof CreateGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$gameId': {
      id: '/vote/$gameId'
      path: '/vote/$gameId'
      fullPath: '/vote/$gameId'
      preLoaderRoute: typeof VoteGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$gameId': {
      id: '/lobby/$gameId'
      path: '/lobby/$gameId'
      fullPath: '/lobby/$gameId'
      preLoaderRoute: typeof LobbyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateGameRoute: CreateGameRoute,
  HostLobbyRoute: HostLobbyRoute,
  JoinRoute: JoinRoute,
  JoinGameRoute: JoinGameRoute,
  LobbyGameIdRoute: LobbyGameIdRoute,
  VoteGameIdRoute: VoteGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
